package constants

const (
	IMAGE_SCN_MEM_EXECUTE     = 0x20000000
	IMAGE_SCN_MEM_READ        = 0x40000000
	IMAGE_SCN_MEM_WRITE       = 0x80000000
	
	// Machine types
	IMAGE_FILE_MACHINE_I386  = 0x014c // Intel 386
	IMAGE_FILE_MACHINE_AMD64 = 0x8664 // AMD64 (K8)
	
	// Directory entry indices for DataDirectory array
	IMAGE_DIRECTORY_ENTRY_EXPORT      = 0
	IMAGE_DIRECTORY_ENTRY_IMPORT      = 1
	IMAGE_DIRECTORY_ENTRY_RESOURCE    = 2
	IMAGE_DIRECTORY_ENTRY_EXCEPTION   = 3
	IMAGE_DIRECTORY_ENTRY_SECURITY    = 4
	IMAGE_DIRECTORY_ENTRY_BASERELOC   = 5
	IMAGE_DIRECTORY_ENTRY_DEBUG       = 6
	IMAGE_DIRECTORY_ENTRY_COPYRIGHT   = 7
	IMAGE_DIRECTORY_ENTRY_GLOBALPTR   = 8
	IMAGE_DIRECTORY_ENTRY_TLS         = 9
	IMAGE_DIRECTORY_ENTRY_LOAD_CONFIG = 10

	// Define DLL_PROCESS_ATTACH for TLS callbacks
	DLL_PROCESS_ATTACH = 1
	// Define DLL_PROCESS_DETACH for DLL unloading
	DLL_PROCESS_DETACH = 0

	// Define the offset of AddressOfCallBacks in the TLS directory
	TLS_CALLBACK_OFFSET_64 = 24
	TLS_CALLBACK_OFFSET_32 = 12

	// Constants for relocations
	IMAGE_REL_BASED_HIGHLOW = 3
	IMAGE_REL_BASED_DIR64   = 10

	// Memory page size
	PAGE_SIZE = 4096
)
