name: Go CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build-test-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.1'
      
      - name: Build test binaries
        shell: cmd
        run: |
          if not exist testdata mkdir testdata
          set GOOS=windows
          set GOARCH=amd64
          go build -o testdata\hello.exe testdata\helloworld.go
          set CGO_ENABLED=1
        
      - name: Run tests
        shell: cmd
        run: |
          set CGO_ENABLED=1
          set GOOS=windows
          echo "Listing tests in pkg directory:"
          cd pkg
          go test -list . -tags windows .
          echo "Running tests..."
          echo "Attempting to run ONLY TestDllExecution (with pre-built DLL) and verbose build/link output..."
          go test -x -v -tags windows . -run "^TestDllExecution$" 