name: Go CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

permissions:
  security-events: write

jobs:
  build-test-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'
      
      - name: Build test binaries
        shell: cmd
        run: |
          if not exist testdata mkdir testdata
          set GOOS=windows
          set GOARCH=amd64
          go build -o testdata\hello.exe testdata\helloworld.go
          set CGO_ENABLED=1
          go build -ldflags="-s -w" -buildmode=c-shared -o testdata\hello.dll testdata\hellodll.go
          
      - name: Check Windows Security Settings
        shell: powershell
        run: |
          Write-Host "Checking DEP settings..."
          Get-ProcessMitigation -System
          Write-Host "Checking Windows Defender settings..."
          Get-MpPreference | Select-Object -Property EnableControlledFolderAccess,AttackSurfaceReductionRules_Ids,AttackSurfaceReductionRules_Actions
          Write-Host "Checking current process privileges..."
          whoami /priv
          Write-Host "Checking process mitigation policy..."
          Get-ProcessMitigation -Name go.exe
        
      - name: Run tests
        shell: cmd
        run: |
          set CGO_ENABLED=1
          set GOOS=windows
          echo "Listing tests in pkg directory:"
          cd pkg
          go test -list . .
          echo "Running tests with verbose output..."
          go test -v . -run "TestExeExecution|TestDllExecution" 2>&1 